version: v2.0

on:
  mr:
    paths-ignore:
      - README.md
    users-ignore:
      - yongyiduan
 
stages:
- jobs:
    all-job-0:
      steps:
      - run: |
          echo "::set-variable name=EVENT::${{ci.event}}"