version: v2.0

on:
  tag:
    tags-ignore:
      - tag_*
    users-ignore:
      - yongyiduan
 
stages:
- jobs:
    all-job-0:
      steps:
      - run: |
          echo "::set-variable name=EVENT::${{ci.event}}"