version: v2.0

on:
  tag:
    tags:
      - tag_*
    from-branches:
      - main
    users:
      - yongyiduan
 
stages:
- jobs:
    all-job-0:
      steps:
      - run: |
          echo "::set-variable name=EVENT::${{ci.event}}"