version: v2.0

# concurrency:
#   group: ${{ ci.branch }} 
 
stages:
- jobs:
    all-job-0:
      steps:
      - checkout: self
      - run: |
          echo "::set-variable name=EVENT::${{ci.event}}"
