version: v2.0

name: 手动触发测试 

on:
  push: 
    branches: 
    - trigger
  manual: enabled  # 是否允许手动触发，缺省时默认为 enabled，可选值： enabled / disabled 

variables:
  a: 
    value: 123
    allow-modify-at-startup: true
    props:
      type: vuex-input
      required: true
  my_val_3:
    value: false
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      label: 我是 BOOL 字段
      type: boolean
      required: true
  my_val_4:
    value: 1,2
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      label: 我是 checkbox 字段
      type: checkbox
      required: true
      options:
        - id: 1
          label: 正式环境
          description: 说明什么情况下发正式
        - id: 2
  my_val_5:
    value: 这是个tips,说明下怎么使用
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      type: tips
      required: true
  my_val_6:
    value: ruotiantang
    allow-modify-at-startup: true  # 手动触发/openapi触发时生效，可选值：true / false，默认为 false
    props:
      type: company-staff-input
      required: true

jobs:
  job_id_1:
    steps:
    - checkout: self
      name: checkout the base repo
      id: step_git
      continue-on-error: true  
    - name: 公共上下文参数
      run: |
        echo 'ci.workspace = ${{ci.workspace}}'
        echo 'ci.token = ${{ci.token}}'
        echo 'ci.pipeline_name = ${{ci.pipeline_name}}'
        echo 'ci.pipeline_id = ${{ci.pipeline_id}}'
        echo 'ci.pipeline_start_time = ${{ci.pipeline_start_time}}'
        echo 'ci.actor = ${{ci.actor}}'
        echo 'ci.commit_author = ${{ci.commit_author}}'
        echo 'ci.build_id = ${{ci.build_id}}'
        echo 'ci.build_num = ${{ci.build_num}}'
        echo 'ci.build_url = ${{ci.build_url}}'
        echo 'ci.build_status = ${{ci.build_status}}'
        echo 'ci.build_fail_tasknames = ${{ci.build_fail_tasknames}}'
        echo 'ci.repo_url = ${{ci.repo_url}}'
        echo 'ci.repo = ${{ci.repo}}'
        echo 'ci.repo_name = ${{ci.repo_name}}'
        echo 'ci.repo_group = ${{ci.repo_group}}'
        echo 'ci.event = ${{ci.event}}'
        echo 'ci.event_content = ${{ci.event_content}}'
        echo 'ci.event_url = ${{ci.event_url}}'
        echo 'ci.ref = ${{ci.ref}}'
        echo 'ci.branch = ${{ci.branch}}'
        echo 'ci.sha = ${{ci.sha}}'
        echo 'ci.sha_short = ${{ci.sha_short}}'
        echo 'ci.commit_message = ${{ci.commit_message}}'
    - name: push上下文参数
      run: |
        echo 'ci.before_sha = ${{ci.before_sha}}'
        echo 'ci.before_sha_short = ${{ci.before_sha_short}}'
  job_id_2:
    steps:
      - name: 打印用户自定义variable
        run: |
          echo 'variables.a = ${{variables.a}}'
          echo 'variables.my_val_1 = ${{variables.my_val_1}}'
          echo 'variables.my_val_3 = ${{variables.my_val_3}}'
          echo 'variables.my_val_4 = ${{variables.my_val_4}}'
          echo 'variables.my_val_2 = ${{variables.my_val_2}}'
          echo 'variables.my_val_5 = ${{variables.my_val_5}}'
          echo 'variables.my_val_6 = ${{variables.my_val_6}}'
