version: v2.0



jobs:
  job_id_1:
    runs-on:
      agent-selector: [linux]
      self-hosted: true
      pool-name: faye
    steps:
    - run: echo "hello local "


resources:
  pools:
    - from: fayewang/ci_test@aaa
      name: faye