version: v2.0



stages:
- name: 预设替换变量
  jobs:
    all-job-0:
      steps:
      - run: |
          rm -rf  ./report
          mkdir ./report
          echo 若天查看报告测试 > ./report/report.txt
          echo "::set-output name=files,type=artifact::./report/*.txt"